# Generated by Django 5.0.7 on 2024-08-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='professor',
            field=models.CharField(max_length=100),
        ),
    ]
