# Generated by Django 5.0.7 on 2024-10-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_section_credit_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('full_course', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=100)),
                ('gpa', models.FloatField()),
                ('a', models.FloatField(blank=True, null=True)),
                ('a_minus', models.FloatField(blank=True, null=True)),
                ('b_plus', models.FloatField(blank=True, null=True)),
                ('b', models.FloatField(blank=True, null=True)),
                ('b_minus', models.FloatField(blank=True, null=True)),
                ('c_plus', models.FloatField(blank=True, null=True)),
                ('c', models.FloatField(blank=True, null=True)),
                ('c_minus', models.FloatField(blank=True, null=True)),
                ('d_plus', models.FloatField(blank=True, null=True)),
                ('d', models.FloatField(blank=True, null=True)),
                ('d_minus', models.FloatField(blank=True, null=True)),
                ('f', models.FloatField(blank=True, null=True)),
                ('withdraws', models.FloatField(blank=True, null=True)),
                ('graded_enrollment', models.FloatField(blank=True, null=True)),
                ('crn', models.CharField(max_length=100)),
                ('credit_hours', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='avg_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
