# Generated by Django 5.0.7 on 2024-10-30 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_gradedistribution_section_avg_gpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionOpenOrClosed',
            fields=[
                ('crn', models.IntegerField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('class_type', models.CharField(max_length=100)),
                ('modality', models.CharField(max_length=100)),
                ('credit_hours', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('exam_code', models.CharField(max_length=100)),
                ('avg_gpa', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionTimeOpenOrClosed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=100)),
                ('begin_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('crn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.sectionopenorclosed')),
            ],
        ),
    ]
